name: cjpower_ble
description: Flutter BLE service for CJPOWER motor controller
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.31.0
  rxdart: ^0.27.7
  equatable: ^2.0.5
  get_it: ^7.6.4
  fl_chart: ^0.68.0
  excel: ^2.0.0
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  image: ^4.3.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#F5A623"
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"
flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png
    - assets/icon/app_icon_foreground.png